### ISSUE TITLE
User sign up page

### ISSUE THREAD

**Issue by hannahcmtucker** [fac-12/Albert-Kennedy#18]
- [x] create form
- [ ] send relevant info to database
- [x] set up encryption etc on backend
- [ ] decide which user data are we going to store
- [ ] send relevant user data to AKT (by email?)
- [x] send relevant information to mentor (scheduled time etc)
- [ ] send appointment reminder to young person

**Comment by lucymk** [comment]
Comment from Tom via email:

I’d just use blank fields rather than drop down lists otherwise we’ll get feedback around imposition of labels, not embracing diversity, etc.

·         Date of birth
·         Town/City – some people will be accessing from rural areas so maybe a different word for this? Location? Area?
·         Gender
·         Sexuality
·         Ethnicity
