### ISSUE TITLE
Content throughout the app 

### ISSUE THREAD

**Issue by lucymk** [fac-12/Albert-Kennedy#71]
@hellotomjohnson is going to send us content for the following pages:

- [x] not 13-25 redirect page
- [x] not LGBT+ redirect page
- [x] in crisis redirect page 
- [x] GDPR "phrases" to be used when asking for data

**Comment by hellotomjohnson** [comment]
@sophielevens @lucymk 

**Not 13-15 redirect page**

If you are not aged 13-25 years old we recommend  contacting these organisations instead:

Stonewall Housing is a specialist lesbian, gay, bisexual and transgender (LGBT) housing advice and support provider. http://www.stonewallhousing.org. 020 7359 5767.

Shelter provides practical assistance, advice, information and advocacy to people experiencing homelessness: http://www.shelter.org.uk. 0808 800 4444

Stonewall can offer information and support for members of the LGBT community: https://www.stonewall.org.uk. 020 7593 1850

**Not LGBT+ redirect page**

If you do not identify as LGBT+ we recommend contacting these organisations instead: 

Shelter provides practical assistance, advice, information and advocacy to people experiencing homelessness: http://www.shelter.org.uk. 0808 800 4444

Childine offer help and advice to anyone under 19 in the UK with any issue they’re going through: https://www.childline.org.uk. 0800 1111.

The Mix is an online service that provides information and support on a range of issues for under 25s in the UK: http://www.themix.org.uk. 0808 808 4994.

**In crisis redirect page**

If you are in crisis, don’t use this site. Use one of these services instead.

If you’re in immediate danger, call emergency services on 999.

If you are having suicidal thoughts, call 999 or Go to your nearest A&E department.

You can also call Samaritans' 24-hour free helpline on 116 123.

National LGBT Domestic Violence Helpline: 0300 999 5428 / 0800 999 5428

LGBT SwitchBoard listen to all kinds of calls, and we take every one seriously: 0300 330 0630

**GDPR wording to be used when asking for data**

AKT is asking for this information because it's important for us to know who is accessing this service so that we can provide the most appropriate support. By completing this form you are consenting to The Albert Kennedy Trust storing a record of your details and contacting you regarding related support. If you wish to withdraw your consent, please contact onlinesupport@akt.org.uk.
