### ISSUE TITLE
Feature: 24 hour reminder email 

### ISSUE THREAD

**Issue by lucymk** [fac-12/Albert-Kennedy#78]
It would be useful for both users and mentors to receive a reminder about their appointment 24 hours in advance. 

This could have the added feature for mentors of being able to cancel if they can no longer make the appointment. Further research (technical spike) will need to be done to research the best way to do this.

**Comment by lucymk** [comment]
spike commencing

**Comment by lucymk** [comment]
This is going to be useful! 
http://www.spacjer.com/blog/2014/02/10/defining-node-dot-js-task-for-heroku-scheduler/

**Comment by lucymk** [comment]
@hellotomjohnson sorry I forgot to mention this earlier! Whenever you get a chance, if you can tell me the content you want for the reminder emails that would be great.

**Comment by hellotomjohnson** [comment]
Hey @lucymk, See below for updated confirmation email copy, new reminder and cancellation emails. 
Also, just in case it’s relevant, we’ve set up a generic online services email account now, which is onlinesupport@akt.org.uk. If you need to put down an email address for queries or things like that, use this one.
Thanks,

---

**Confirmation email for young person:**

Subject: AKT online mentoring appointment confirmed

Hi there,

This email is confirmation of your appointment with **[insert mentor name]** on **[insert date]** at **[insert time]**.

At the time of your appointment, click on this link: **[insert link – OR can we create a button?]**. This link will take you to a private chat room where your online mentor will be waiting for you. They will greet you and ask whether you want to continue using live chat or would prefer to use audio or video.

If you need to cancel or rearrange your appointment, please let us know by going to **[….could you specify the process please? Is it just simply saying go to the website/app or can we add a button?]**. 

At the end of the session your online mentor will ask you to complete this feedback form **[insert this link: http://bit.ly/aktfeedback]**. This is to help AKT understand if you would like any more support and to improve AKT services, so we’d be really grateful if you could fill it in after your session.

The Albert Kennedy Trust will treat everything you say confidentially. However, if your safety or the safety of someone else is at risk, we are obliged to disclose relevant information with organisations such as the police or social services. If you are in immediate danger you should call emergency services on 999.

If you have any questions, concerns or need any additional help, you can contact The Albert Kennedy Trust directly by emailing onlinesupport@akt.org.uk.

Best wishes,

The Albert Kennedy Trust
https://www.akt.org.uk/

----------------------------

**Confirmation email for mentor:**

Subject: New AKT online mentoring appointment 

Hi there,

One of your time slots has been booked! You are now scheduled to connect with **[insert young person’s first name]** on **[insert date]** at **[insert time]**. Here are some additional details about them:

- **Location:** **[just town or postcode – no specific addresses]**
- **Age:** 
- **Sexuality:** 
- **Gender:**
- **Support areas:**
- **Additional information:**

At the time of your appointment, click on this link: **[insert link]**. It is advised that you click on the link a few minutes before the time of your appointment so that you can be there greet the young person upon their arrival. Please allow 15 minutes for the young person to join as they may be running late. 

If you have any questions about this session, would like some support preparing, or would like to pass this on to an AKT practitioner, please contact onlinesupport@akt.org.uk or call the London office on 020 7831 6562.

Please be sure to follow the steps below during your session. 
1.	**When young person arrives, greet them** and asks for their name and what they would like to talk about, just to confirm that they are the expected young person.
2.	Ask them whether they would like to continue using **live chat, or talk using audio or video** instead. If they would like an audio or video conversation, share your unique appear.in link with them so that you can both click through to that virtual space. Please note that they can only use appear.in if they are on a computer. If they are on their phone, they can only use live chat.
3.	**Facilitate your online sessio**n with young person – no personal contact details exchanged.
4.	When **closing the session, summarise next steps** for young person and confirm whether young person would like another session.
5.	**Asks young person to complete this feedback form** and share the link with them: http://bit.ly/aktfeedback. The young person has also been given this link in their appointment confirmation email. AKT will share useful and appropriate content with you afterwards.
6.	**Wait for young person to leave** the online room before leaving yourself.
7.	**Complete session review** straight after your session: https://goo.gl/forms/uEdXig4YxBfptu9l2. This is received by AKT and you will receive a copy as well.

Thank you, enjoy your session, and best wishes,

The Albert Kennedy Trust
https://www.akt.org.uk/

----------------------------

**Reminder email for young person:**

Subject: Reminder: Upcoming AKT online mentoring appointment

Hi there,

This email is a reminder of your appointment with **[insert mentor name]** on **[insert date]** at **[insert time]**.

At the time of your appointment, click on this link: **[insert link – OR can we create a button?]**. This link will take you to a private chat room where your online mentor will be waiting for you. They will greet you and ask whether you want to continue using live chat or would prefer to use audio or video.

If you need to cancel or rearrange your appointment, please let us know as soon as possible by going to **[….could you specify the process please? Is it just simply saying go to the website/app or can we add a button?]**

At the end of the session your online mentor will also ask you to complete this feedback form **[insert this link: http://bit.ly/aktfeedback]**. This is to help AKT understand if you would like any more support and to improve AKT services, so we’d be really grateful if you could fill it in after your session.

The Albert Kennedy Trust will treat what you say confidentially. However, if your safety or the safety of someone else is at risk, we are obliged to disclose relevant information with organisations such as the police or social services. If you are in immediate danger you should call emergency services on 999.

If you have any questions, concerns or need any additional help, you can contact The Albert Kennedy Trust directly by emailing onlinesupport@akt.org.uk.

Best wishes,

The Albert Kennedy Trust
https://www.akt.org.uk/

----------------------------

**Cancellation email for mentor:**

Subject: Cancelled AKT online mentoring appointment 

Hi there,

[Young person’s first name] has cancelled their appointment with you, which was scheduled for [insert date] at [insert time]. 
	
They may be in touch again soon to book another appointment, or it may be that they no longer require support from us. Either way, thank you so much for offering your time to support this young person.

If you have any concerns, please email: onlinesupport@akt.org.uk

Best wishes,

The Albert Kennedy Trust
https://www.akt.org.uk/

**Comment by hellotomjohnson** [comment]
**Cancellation email for mentor**

Subject: Cancelled AKT online mentoring appointment

Hi there,

Thank you for letting us know you can no longer make your online mentoring appointment. Your appointment for [insert date] at [insert time] has now be cancelled.

If you would like to rearrange, simply book another appointment with the mentor of your choosing: **[insert link to inter-AKT app]**

If you would rather talk to AKT directly or your issue is urgent, please email please email onlinesupport@akt.org.uk or reach out to the AKT office that is closest to you geographically: https://www.akt.org.uk/contact

Best wishes,

The Albert Kennedy Trust
https://www.akt.org.uk/
